#+TITLE: README.org
#+AUTHOR: TPH Gang
#+STARTUP: overview

* TPHmacs

  The Emacs brigade presents =TPHmacs=, The Programmers hangout's own little
  configuration for curious individuals.

  It will include the bare minimum in order to spark some sort of curiosity of how the
  ecosystem around Emacs works and maybe get you started on your own configuration with
  this as a starting point.

  Now, there are many different kinds of users and as a result, there is no one
  standard to follow in terms of configuration. You should use what fits your needs and
  wants the best. Ergo, we've decided to not give you a configuration!

  Instead, we provide the bare basics in =.emacs.d=. Next, we give sample, literate,
  configurations for various packages we use and found helpful. This is so you can
  check them out and learn from them.

* Installation
  Just insert the folder content into ~.emacs.d~ and you are good to go.

  Note: it may be worth looking into [[https://www.gnu.org/software/stow/manual/stow.html][GNU stow]].

* Learn more
  if you are new to Emacs, be sure to go through the tutorial in order
  to learn the absolute basics in order to navigate and use Emacs.

  You can get there by typing ~C-h t~ which is ~Ctrl-h and then t~.

  And if you have gone through the tutorial and wants to know more, then
  [[https://www.emacswiki.org/][The Emacs Wiki]] should hold a lot of answers to your every need.
